### ISSUE TITLE
Update speakers' layout to V3 design

### ISSUE THREAD

**Issue by absynthmind** [designing-experiences/xd-conf#4]
The V3 design shows a different, and more attractive, design for the individual speaker placeholder. Update the current implementation to this design (and link to the appropriate HTML resource in the /speakers folder).

**Comment by wouterd** [comment]
Where can I find that V3 design?

**Comment by absynthmind** [comment]
It's in the /0xD/Context/Branding/Landingspagina folder on Dropbox.

**Comment by bobvanluijt** [comment]
@wouterd I'm on it...

**Comment by bobvanluijt** [comment]
Fixed: https://github.com/designing-experiences/xd-conf/commit/2ba609fe726a7f0b8d156b32387c7b6bbdf8ff8a
