### ISSUE TITLE
Adjust/process individual speaker's image

### ISSUE THREAD

**Issue by absynthmind** [designing-experiences/xd-conf#5]
The images for the various speakers come in various sizes and of varying (colour) quality. Adjust the images so that they fit into the assigned placeholder; process them by an imaging tool if so needed.

This issue is related to issue [#4](https://github.com/designing-experiences/xd-conf/issues/4)

**Comment by bobvanluijt** [comment]
Fixed: https://github.com/designing-experiences/xd-conf/commit/5df6c31a5f0bdb897a47bdd07e8a59f68630bf11
