### ISSUE TITLE
Broken navigation on child pages

### ISSUE THREAD

**Issue by absynthmind** [designing-experiences/xd-conf#6]
The navigation links for each child page (like a speaker's page) is broken. The anchor attaches to the current (child) page, instead of the parent page.

**Comment by bobvanluijt** [comment]
Not sure I follow, I can't find any broken anchor links on http://www.ing-experience-design.com/xd-conf

**Comment by bobvanluijt** [comment]
Note, I've set the relative urls to /#location. If you test locally it points to `file:///#location` but works correctly on the website.

https://github.com/designing-experiences/xd-conf/commit/e9da6b0b91723d51a8e0d230dc03496246023743

**Comment by absynthmind** [comment]
Replacing the existing (main page's) navigation items with a shortened list is not really a solution. There's is actual value in the main navigation, even (or especially) on the child pages.

**Comment by bobvanluijt** [comment]
fixed https://github.com/designing-experiences/xd-conf/commit/c6bafdc2ccff458639dcced5ad1a595e38911fb7
